### ISSUE TITLE
Incorrect payment prefix when using "Free Orders number series"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-advanced-sequential-order-numbers#2]
Found a bit of a weird edge case here. 

If you have "Free Orders number series" checked in the Order Numbers settings, and then you renew a license using the "Renew Payment and renew Subscription" button in the Subscription single view, the payment will be prefixed with the "free" prefix, even if the amount entered is greater than $0. It should use the "completed" prefix. 

This does not happen if you renew the payment on the front-end as a customer. It also does not happen if you have the "Free Orders number series" unchecked.

For context, here are the prefix settings I am referring to:
<img width="915" alt="screen shot 2017-11-13 at 11 32 30 am" src="https://user-images.githubusercontent.com/1638128/32736924-b1884c16-c866-11e7-9fb1-7ef2b5884303.png">

Here is a payment that was renewed through the Subscription single view and it is over $0, but still uses the "free" prefix:

<img width="1270" alt="screen shot 2017-11-13 at 11 35 52 am" src="https://user-images.githubusercontent.com/1638128/32736978-d6f515f6-c866-11e7-8bf4-0da1d201b5fa.png">

**Comment by sunnyratilal** [comment]
I've tracked this down to [this line](https://github.com/easydigitaldownloads/edd-advanced-sequential-order-numbers/blob/master/edd-son.php#L254) but hitting a roadblock as to why `edd_get_payment_total` isn't returning the correct amount.

**Comment by sunnyratilal** [comment]
After further debugging, I believe this to be an issue with EDD Recurring.

[This is the code](https://github.com/easydigitaldownloads/edd-recurring/blob/master/includes/admin/subscriptions.php#L708) that gets executed when a new subscription is being created manually from the admin. The line highlighted sets the `amount` on the payment so when running `edd_get_payment_total()`, we get the expected total.

[This is the code that runs](https://github.com/easydigitaldownloads/edd-recurring/blob/master/includes/edd-subscription.php#L336-L379) when we add a payment to an existing subscription. Notice that the `total` isn't set on the `EDD_Payment` object hence running `edd_get_payment_total` returns 0 which is why the prefix for the free orders is prepended.

**Comment by kerijacoby** [comment]
https://secure.helpscout.net/conversation/465908004/70260?folderId=180504
